apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: laravel-app
  namespace: argocd
spec:
  project: default

  source:
    # ↓ তোমার GitHub repo URL দাও
    repoURL: https://github.com/firoj7github/Aws-Terraform-K8s-AgroCD-CI-CD-Project-Deploy-Full-Ready-Setup-2026
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: laravel-prod

  syncPolicy:
    automated:
      prune: true       # পুরনো resource delete করবে
      selfHeal: true    # manual change হলে revert করবে
    syncOptions:
      - CreateNamespace=true
