apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: laravel-prod
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "StrongPass123!"
  MYSQL_DATABASE:      "aws_laravel"
  MYSQL_USER:          "laravel_user"
  MYSQL_PASSWORD:      "LaravelPass123!"