apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: laravel-prod
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP   # শুধু K8s এর ভেতরে access হবে