apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: laravel-prod
type: Opaque
stringData:
  APP_KEY:       "base64:vOYCcV4VAOiCOEw2Pv12Hi2qfqmkjiflCU3aM3EDujE="
  DB_CONNECTION: "mysql"
  DB_HOST:       "mysql-service"   # ← K8s service name
  DB_PORT:       "3306"
  DB_DATABASE:   "aws_laravel"
  DB_USERNAME:   "laravel_user"
  DB_PASSWORD:   "LaravelPass123!"