apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: laravel-prod
spec:
  selector:
    app: laravel
  type: LoadBalancer   # AWS automatically ELB বানাবে
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
